### ISSUE TITLE
Comment

### ISSUE THREAD

**Issue by DuskStarGITHUB** [JacksonUptain/JacksonUptain#2]
Hello, your website caught my attention (https://jacksonuptain.github.io/Parallax-Effect-FullCode-From-TrueCoderYT/3D-Parallax-Website-in-JavaScript-main/index.html), you mention that it will come soon, but if there is a point that I want to highlight and that should be resolved if you have not yet resolved it, it is the resources, that important factor, your website weighs too much because of the images, you should optimize them and use the webp format and related to that format, this is Because on mobile it lags too much on a device with a 4 GB Ram HelioG80 processor, if the web is not optimized the experience for generic users will not be good, there is lag and slow loading, I hope this helps you.

**Comment by JacksonUptain** [comment]
Thanks for the feedback, It was really an experiment, but your welcome to fork it/ download the code and do whatever you like with it. If you do feel free to email me at jackson.uptain@gmail.com

**Comment by JacksonUptain** [comment]
Thanks!

**Comment by DuskStarGITHUB** [comment]
Thanks for the permission but I'm fine, they just wanted to raise the possibility of an improvement, which is the format of the images, nothing more, good night/afternoon/day.

**Comment by JacksonUptain** [comment]
Thank you…and the same to you. Good afternoon/evening/night/…whatever
